#!/bin/bash

function eql0d {

local _usage
local _cores
local _reset
local _debug
local _restart
local _print_and_quit
local _verbose
local _command

_usage=$'Usage: eql0d (-rRdb) (-n value) <filename1> ... <filenameN>
	-n <CORES>    to run on <CORES> cores.
	-b            to run in batch mode: calculations launched in parallel.
	-r            to run in restart mode: calculation restarts at last point in time.
	-R            to run in restart & reset mode: calculation restarts from the beginning.
	-d            to run in debugging mode: use existing depmtx_*.m files without calling Serpent
        -p            to launch EQL0D, print Material compositions (*.txt and *.serp) and quit
        -v            to run in verbose mode (more detailed log file)'
_cores=1; _reset=false; _debug=false; _restart=false;  _print_and_quit=false; _verbose=false;

while getopts "n:rRdpv" OPT; do
    case $OPT in
#        b) _batch=true ;;
        r) _restart=true ;;
        R) _reset=true ;;
        d) _debug=true ;;
        n) _cores="$OPTARG" ;;
        p) _print_and_quit=true ;;
        v) _verbose=true ;;
        \?) echo "${_usage}" >&2
        exit 1 ;;
        :) >&2 echo "Error: Missing parameter for $OPTARG !"
        exit 1 ;;
    esac
done
shift $((OPTIND-1))

# Filename check
if [[ -z "$1" ]] ; then
	>&2 echo "Error: no filename given."
	exit 1
fi

_command="Cases={''"
for file in "$@" ; do
	_command+=",'$file'"
done
_command+="};addpath('$(dirname $0)');Cases(1)=[];EQL0Dlauncher(Cases,$_cores,$_verbose,$_print_and_quit,$_restart,$_reset,$_debug);exit"

matlab -nodisplay -nojvm -nosplash -nodesktop -r "$_command" &> EQL0D.log &
exit 0

}
